#include "Memento.h"




void Memento::getState()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--440fe0d:168a8d2aefd:-8000:000000000000087A begin
{
}
// section 127-0-1-1--440fe0d:168a8d2aefd:-8000:000000000000087A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Memento::setState()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--440fe0d:168a8d2aefd:-8000:000000000000087C begin
{
}
// section 127-0-1-1--440fe0d:168a8d2aefd:-8000:000000000000087C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
