#include "Originator.h"

/*
 * 
 */



void Originator::setMemento()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--440fe0d:168a8d2aefd:-8000:000000000000086D begin
{
}
// section 127-0-1-1--440fe0d:168a8d2aefd:-8000:000000000000086D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Originator::createMemento()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--440fe0d:168a8d2aefd:-8000:000000000000086F begin
{
}
// section 127-0-1-1--440fe0d:168a8d2aefd:-8000:000000000000086F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
